name: Build

on: 
  push:
    branches: [ build_windows ]

  pull_request:
    branches: [ build_windows ]

env:
  TARGET: Project_opengl_exe # Should be the name of the target you created in your CMakeLists.txt and want to build and run

jobs:
  Windows_MSVC_Release:
    name: Windows MSVC Release
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
      with:
          submodules: recursive

    - name: Configure CMake
      run: cmake .\ -B ${{github.workspace}}\build -D CMAKE_C_COMPILER=cl -D CMAKE_CXX_COMPILER=cl

    - name: Build
      run: cmake --build ${{github.workspace}}\build --config Release --target ${{env.TARGET}}

    - name: Run
      run: ${{github.workspace}}\build\Release\${{env.TARGET}} -nogpu