name: Build

on: workflow_dispatch

env:
  TARGET: Project_opengl # Should be the name of the target you created in your CMakeLists.txt and want to build and run

jobs:
  Windows_Clang_Release:
    name: Windows Clang Release
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Configure CMake
      run: cmake .\ -B ${{github.workspace}}\build -T ClangCL -D CMAKE_C_COMPILER=cl -D CMAKE_CXX_COMPILER=cl

    - name: Build
      run: cmake --build ${{github.workspace}}\build --config Release --target ${{env.TARGET}}_exe

    - name: Zip files
      uses: vimtor/action-zip@v1
      with:
        files: ${{github.workspace}}\bin\Release\
        dest: OpenGL-Windows.zip
      
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: OpenGL-Windows.zip